Added index.html file
minds0987/calculaty pull request #1
Opened 2021-04-25 15:23 UTC by nived-dev

@dev-minds0987 
I want you to merge this pull request. If you think there is no error while debugging. 
If you have found an error, please let me know.

2021-04-25 16:06 UTC, dev-minds0987 requested changes
Check the code tomorrow and get back to me ASAP

2021-04-25 16:06 UTC, dev-minds0987 commented on index.html
> +<meta charset="UTF-8">
Hello @nived-dev , I am very impressed that you have submitted the code within 6 days but the favicon image cannot be seen **try checking the code again.** 
Anyway considering your work, I am considering this merge request

2021-04-25 16:07 UTC, dev-minds0987 commented
@nived-dev Pull requested will be merged but please make the changes and get back to me

2021-04-25 16:08 UTC, closed without merging

2021-05-07 15:32 UTC, nived-dev commented
Branch deleted from github.com/minds0987.
For more info: https://github.com/minds0987/calculaty/pull/1
OR
mailto:minds0987@gmail.com